openapi: 3.0.0
info:
  title: Backend API
  description: API для управления коробками, паллетами, проверками и сортировкой.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Локальный сервер

paths:
  /cargo/handleCargo:
    get:
      summary: Получение данных по SSCC
      description: Выполняет логику обработки на основе SSCC, извлекая данные из связанных таблиц. Возвращает `v.rsd_code` и `tr.rsd_every_day_num`, либо сообщение об ошибке.
      parameters:
        - in: query
          name: sscc
          required: true
          schema:
            type: string
            example: "120200000053183753"
          description: Уникальный идентификатор SSCC.
      responses:
        '200':
          description: Успешный ответ или неудачные сценарии
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                    description: Указывает, успешен ли запрос (`true` или `false`).
                  message:
                    type: string
                    nullable: true
                    example: "Отсканируйте коробку"
                    description: Сообщение об ошибке или успехе.
                  data:
                    type: object
                    nullable: true
                    description: Данные возвращаются только при `success: true`.
                    properties:
                      rsd_code:
                        type: string
                        example: "БЛ"
                        description: Код RSD.
                      rsd_every_day_num:
                        type: integer
                        example: 4
                        description: Номер, обновляемый ежедневно.
              examples:
                success:
                  value:
                    success: true
                    message: "Данные успешно обработаны"
                    data:
                      rsd_code: "БЛ"
                      rsd_every_day_num: 4
                error_missing_sscc:
                  value:
                    success: false
                    message: "Параметр sscc обязателен"
                error_cargo_unit_not_found:
                  value:
                    success: false
                    message: "CARGO_UNIT_ID не найден"
                error_multiple_records:
                  value:
                    success: false
                    message: "Отсканируйте коробку"
                error_server:
                  value:
                    success: false
                    message: "Ошибка сервера"
                    error: "Описание ошибки"
  /tm/validateBox:
    post:
      summary: Проверка коробки по адресу
      description: Проверяет, подходит ли коробка (по SSCC) к адресу (паллета).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sscc:
                  type: string
                  example: "020199010440489960"
                  description: Уникальный идентификатор коробки (SSCC).
                pallet_scanned:
                  type: string
                  example: "BL-7"
                  description: Адрес паллеты (сканированный).
      responses:
        '200':
          description: Коробка подходит к адресу
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Коробка подходит к адресу"
                  valid:
                    type: boolean
                    example: true
        '400':
          description: Ошибка валидации или неверный формат данных
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Неверный формат адреса (ожидается формат BL-7)"
        '404':
          description: Данные не найдены для указанного SSCC
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Данные не найдены для указанного SSCC"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ошибка сервера"
                  error:
                    type: string
                    example: "Описание ошибки"

  /tm/addFullInfo:
    post:
      summary: Добавление данных в TM_full_info
      description: Добавляет запись в таблицу TM_full_info с обязательными данными.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                eo:
                  type: string
                  example: "EO123456"
                  description: Код EO.
                order_name:
                  type: string
                  example: "Order001"
                  description: Название заказа.
                zayavka:
                  type: string
                  example: "Zayavka001"
                  description: Название заявки.
                sn:
                  type: string
                  example: "SN123456"
                  description: Серийный номер (SN).
                address:
                  type: string
                  example: "Main Street 123"
                  description: Адрес клиента.
                client:
                  type: string
                  example: "Client A"
                  description: Имя клиента.
      responses:
        '200':
          description: Данные успешно добавлены
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Данные успешно добавлены"
                  id:
                    type: integer
                    example: 101
        '400':
          description: Ошибка валидации данных
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Все поля, кроме mesto, обязательны"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ошибка сервера"
                  error:
                    type: string
                    example: "Описание ошибки"

  /tm/getFullInfo:
    get:
      summary: Получение списка из TM_full_info
      description: Возвращает список данных из таблицы TM_full_info.
      responses:
        '200':
          description: Список успешно получен
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Список успешно получен"
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        eo:
                          type: string
                          example: "EO123456"
                        order_name:
                          type: string
                          example: "Order001"
                        zayavka:
                          type: string
                          example: "Zayavka001"
                        sn:
                          type: string
                          example: "SN123456"
                        address:
                          type: string
                          example: "Main Street 123"
                        client:
                          type: string
                          example: "Client A"
                        Cargo_UNIT_ID:
                          type: string
                          example: "Client A"
                        mesto:
                          type: integer
                          example: 1
                        ID:
                          type: integer
                          example: 101
        '404':
          description: Список пуст
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Список пуст"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ошибка сервера"
                  error:
                    type: string
                    example: "Описание ошибки"

  /sortedData:
    get:
      summary: Получение данных сортировки по SSCC
      description: Возвращает данные на основе указанного SSCC из базы данных.
      parameters:
        - in: query
          name: sscc
          required: true
          schema:
            type: string
            example: "020199010440489960"
          description: Уникальный идентификатор коробки (SSCC).
      responses:
        '200':
          description: Успешный ответ с данными
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    rsd_code:
                      type: string
                      example: "БЛ"
                      description: Код RSD.
                    rsd_every_day_num:
                      type: integer
                      example: 4
                      description: Номер, обновляемый ежедневно.
        '400':
          description: Параметр SSCC отсутствует
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Параметр sscc обязателен"
        '404':
          description: Данные не найдены для указанного SSCC
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Данные не найдены для указанного SSCC"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ошибка сервера"
                  error:
                    type: string
                    example: "Описание ошибки"

  /completeSort:
    post:
      summary: Завершение сортировки
      description: Добавляет данные о завершении сортировки в базу данных.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                palletNumber:
                  type: string
                  example: "KR-5-21.1"
                  description: Уникальный номер паллеты.
                items:
                  type: array
                  items:
                    type: string
                  example: ["item1", "item2", "item3"]
                  description: Список элементов, входящих в паллету.
      responses:
        '200':
          description: Сортировка успешно завершена
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Сортировка завершена"
        '400':
          description: Ошибка в запросе
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Необходимо указать palletNumber и items"
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Ошибка сервера"
                  error:
                    type: string
                    example: "Описание ошибки"